### ISSUE TITLE
Not working in combination with Doc Type Grid Editor Package

### ISSUE THREAD

**Issue by Vrijdagonline** [rasmusjp/umbraco-multi-url-picker#28]
The multi url picker isn't working with the Doc Type Grid Editor Package https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor

The problem is that when you select or enter an Url in the picker it closes the current dialog but it also closes the Doc Type Grid Editor dialog.

**Comment by Vrijdagonline** [comment]
Pull Request for this issue:
#29

**Comment by jezhomegit** [comment]
Great if it can be fixed in the package. There is a good explanation (and temporary fix) that worked for me here: https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/63654-Multi-Url-Picker-not-working-[And-Solution]

Just change it from CloseAll () to Close ().
Also remember to rebuild solution.

**Comment by rasmusjp** [comment]
This is fixed in v1.3.0
